try:
    print(x)
except:
    print('an exception occured')
